
  <?php View::content() ?> 
  <h3>Abogados</h3>
  <!--
  <ul>
     
  <?php foreach($listAbogados->items as $item) : ?> 
  <li>
    <strong><?= $item->id ?> - <?= $item->nombre ?></strong> 
    <?= Html::linkAction("editar/$item->id/", 'Editar') ?> 
    <?= Html::linkAction("eliminar/$item->id/", 'Borrar') ?> 
    <?= Html::linkAction("ver/$item->id/", 'Ver') ?> 
      
  </li>
  <?php endforeach ?>
  </ul>
     !-->
  <table BORDER  WIDTH='500'>

  <tr>

    <th>ID</th>

    <th>Nombre</th>

    <th>Acciones</th>

  </tr>
  <?php foreach($listAbogados->items as $item) : ?> 

  <tr>

    <td><?= $item->id ?></td>

    <td><?= $item->nombre ?></td>

    <td>
    <?= Html::linkAction("editar/$item->id/", 'Editar |') ?> 
    <?= Html::linkAction("eliminar/$item->id/", 'Borrar |') ?> 
    <?= Html::linkAction("ver/$item->id/", 'Ver') ?> 
    </td>

  </tr>
  <?php endforeach ?>

  
</table>


  
   
  <?php if($listAbogados->prev) echo Html::linkAction("index/$listAbogados->prev/", '<< Anterior |') ?> 
  <?php if($listAbogados->next) echo Html::linkAction("index/$listAbogados->next/", 'Proximo >>') ?> 
</div>